# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/predict
Content-Type: application/json

{
    "gender": "Male",
    "age": 22,
    "work_pressure": 3,
    "job_satisfaction": 3,
    "sleep_duration": "More than 8 hours",
    "dietary_habits": "Moderate",
    "suicidal_thoughts": "No",
    "work_hours": 12,
    "financial_stress": 5,
    "family_mental_health": "No"
}
###